
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;

INSERT INTO public.products (slug, name, category, price_per_yard, short_description, description, delivery_notes, image_path, sort_order) VALUES
('black-mulch','Black Mulch','Mulch',75.00,'Premium dyed black mulch — bold contrast for gardens and beds.','Our Black Mulch is a beautifully dyed hardwood mulch that delivers a striking, rich, jet-black finish to flower beds and tree wells. It helps retain soil moisture, suppress weeds, and insulate plant roots through changing seasons. Coverage: 1 yard covers approximately 100 sq ft at 3" depth.','Available for delivery and pickup. Sold by the cubic yard.','black-mulch.jpg',10),
('cedar-mulch','Cedar Mulch','Mulch',55.00,'Naturally aromatic cedar mulch — repels insects and lasts.','Cedar Mulch is a natural, untreated wood mulch known for its distinct aroma and natural insect-repelling properties. It decomposes slowly, making it an economical, long-lasting choice for residential and commercial landscapes.','Available for delivery and pickup. Sold by the cubic yard.','cedar-mulch.jpg',20),
('crystal-white-rock','Crystal White Rock','Decorative Rock',390.00,'Premium bright white decorative rock for high-end landscapes.','Crystal White Rock is a luxurious, bright white decorative stone that adds a clean, elegant accent to any landscape. Ideal for water features, modern garden designs, and statement borders.','Premium product. Available for delivery and pickup. Sold by the cubic yard.','crystal-white-rock.jpg',30),
('garden-mix','Garden Mix 3-1-1','Soil',60.00,'Balanced blend of topsoil, peat and compost for healthy gardens.','Garden Mix 3-1-1 is a balanced blend of premium topsoil, peat moss, and compost. Perfect for new garden beds, vegetable gardens, and amending existing soil.','Available for delivery and pickup. Sold by the cubic yard.','garden-mix.jpg',40),
('limestone-20-30mm','Limestone 20-30mm','Limestone',144.00,'Medium crushed limestone — great for paths and drainage.','20-30mm crushed limestone is a versatile aggregate ideal for pathways, French drains, and decorative borders.','Available for delivery and pickup. Sold by the cubic yard.','limestone.jpg',50),
('limestone-25mm','Limestone 25mm','Limestone',132.00,'25mm crushed limestone for general landscaping use.','25mm crushed limestone is a workhorse aggregate suitable for base material, driveways, and pathways.','Available for delivery and pickup. Sold by the cubic yard.','limestone.jpg',60),
('limestone-30-65mm','Limestone 30-65mm','Limestone',144.00,'Larger crushed limestone for drainage and visual impact.','30-65mm limestone provides excellent drainage and a chunky, natural look perfect for dry creek beds and erosion control.','Available for delivery and pickup. Sold by the cubic yard.','limestone.jpg',70),
('limestone-75-100mm','Limestone 75-100mm','Limestone',148.00,'Large limestone for retaining edges and bold features.','Large 75-100mm limestone is ideal for retaining wall fill, riprap, and bold decorative use.','Available for delivery and pickup. Sold by the cubic yard.','limestone.jpg',80),
('limestone-dust-10-minus','Limestone Dust (10 Minus)','Limestone',124.00,'Fine limestone screening — perfect base for pavers.','Limestone Dust (10 Minus) compacts to a firm, level surface, making it the ideal base material for pavers, flagstone, and artificial turf.','Available for delivery and pickup. Sold by the cubic yard.','limestone.jpg',90),
('majestic-midnight-20mm','Majestic Midnight 20mm','Decorative Rock',165.00,'Sleek 20mm dark basalt — striking modern accent stone.','Majestic Midnight 20mm is a refined dark basalt rock that brings drama and sophistication to contemporary landscapes.','Available for delivery and pickup. Sold by the cubic yard.','majestic-midnight.jpg',100),
('majestic-midnight-30-65mm','Majestic Midnight 30-65mm','Decorative Rock',170.00,'Medium dark basalt — modern statement rock.','30-65mm Majestic Midnight is perfect for water features, modern garden borders, and dry creek beds.','Available for delivery and pickup. Sold by the cubic yard.','majestic-midnight.jpg',110),
('majestic-midnight-40mm','Majestic Midnight 40mm','Decorative Rock',168.00,'40mm dark basalt for bold, contemporary landscape designs.','Majestic Midnight 40mm offers a refined, uniform look ideal for high-impact modern landscapes.','Available for delivery and pickup. Sold by the cubic yard.','majestic-midnight.jpg',120),
('nugget-medium-bark-mulch','Nugget Medium Bark Mulch','Mulch',100.00,'Chunky natural bark mulch — long-lasting decorative cover.','Nugget Medium Bark Mulch features larger natural bark pieces that resist decomposition and provide great visual texture.','Available for delivery and pickup. Sold by the cubic yard.','nugget-bark.jpg',130),
('pine-mulch','Pine Mulch','Mulch',44.00,'Affordable natural pine mulch — value choice for large beds.','Pine Mulch is an economical, natural option for covering large areas. Lightweight and easy to spread.','Available for delivery and pickup. Sold by the cubic yard.','pine-mulch.jpg',140),
('play-sand','Play Sand','Sand & Gravel',90.00,'Clean, fine sand — safe for sandboxes and playgrounds.','Washed and screened play sand suitable for sandboxes, play areas, and decorative use. Free of sharp debris.','Available for delivery and pickup. Sold by the cubic yard.','play-sand.jpg',150),
('purple-spark-40mm','Purple Spark 40mm','Decorative Rock',330.00,'Premium iridescent purple decorative rock — show-stopper.','Purple Spark 40mm is a rare, premium decorative rock with subtle iridescent purple sparkle. A true centerpiece stone.','Premium product. Available for delivery and pickup. Sold by the cubic yard.','purple-spark.jpg',160),
('radon-rocks-20mm','Radon Rocks 20mm','Decorative Rock',77.00,'Warm reddish-brown 20mm decorative rock.','Radon Rocks 20mm bring warm earth tones to gardens, paths, and borders. Excellent for naturalistic designs.','Available for delivery and pickup. Sold by the cubic yard.','radon-rock.jpg',170),
('red-mulch','Red Mulch','Mulch',75.00,'Vibrant dyed red mulch — bold curb appeal.','Red Mulch delivers a vibrant, long-lasting red color that makes greenery pop.','Available for delivery and pickup. Sold by the cubic yard.','red-mulch.jpg',180),
('road-crushed-20mm','Road Crushed 20mm','Sand & Gravel',57.00,'Compacted road crush — driveway and base material.','Road Crushed 20mm compacts firmly and is the standard choice for driveways, parking pads, and sub-base.','Available for delivery and pickup. Sold by the cubic yard.','road-crush.jpg',190),
('rundle-50-90mm','Rundle 50-90mm','Decorative Rock',232.00,'Large Rundle river rock — warm rustic centerpiece stone.','Rundle 50-90mm features warm, multi-tone river-smoothed stones perfect for water features and bold borders.','Available for delivery and pickup. Sold by the cubic yard.','rundle-rock.jpg',200),
('rundle-rock-20mm','Rundle Rock 20mm','Decorative Rock',217.00,'20mm Rundle river rock — soft tones, smooth finish.','Rundle Rock 20mm is a beautiful, warm-toned river rock ideal for borders, pathways, and decorative beds.','Available for delivery and pickup. Sold by the cubic yard.','rundle-rock.jpg',210),
('rundle-rock-40mm','Rundle Rock 40mm','Decorative Rock',228.00,'40mm Rundle river rock — bold warm-tone accent stone.','Rundle Rock 40mm features larger river-tumbled stones in warm earth tones.','Available for delivery and pickup. Sold by the cubic yard.','rundle-rock.jpg',220),
('topsoil','Topsoil','Soil',28.00,'Screened topsoil — great for lawns, leveling and fill.','Quality screened topsoil ideal for lawn establishment, leveling low spots, and filling raised beds.','Available for delivery and pickup. Sold by the cubic yard.','topsoil.jpg',230),
('wash-rocks-20mm','Wash Rocks 20mm','Sand & Gravel',89.00,'20mm washed round river rocks.','Wash Rocks 20mm are clean, washed, multi-tone round river rocks great for drainage and decoration.','Available for delivery and pickup. Sold by the cubic yard.','wash-rock.jpg',240),
('wash-rocks-40-50mm','Wash Rocks 40-50mm','Sand & Gravel',102.00,'40-50mm washed river rocks.','Larger Wash Rocks for bolder decorative applications and drainage.','Available for delivery and pickup. Sold by the cubic yard.','wash-rock.jpg',250),
('wash-rocks-40mm','Wash Rocks 40mm','Sand & Gravel',95.00,'40mm washed round river rocks.','Mid-sized washed river rocks ideal for borders and dry creek beds.','Available for delivery and pickup. Sold by the cubic yard.','wash-rock.jpg',260),
('wash-rocks-50-100mm','Wash Rocks 50-100mm','Sand & Gravel',110.00,'Large 50-100mm washed river rocks.','Premium large washed river rocks for water features and statement landscaping.','Available for delivery and pickup. Sold by the cubic yard.','wash-rock.jpg',270);

INSERT INTO public.blog_posts (slug, title, excerpt, content, cover_image) VALUES
('how-to-calculate-mulch','How to Calculate How Much Mulch You Need','A simple guide to measuring your beds and ordering the right amount of mulch — no waste, no shortfall.','To calculate the volume of mulch you need, measure the length and width of your bed in feet, multiply them, then multiply by the depth in feet (3 inches = 0.25 ft). Divide the result by 27 to get cubic yards. Our online volume calculator on every product page does this for you automatically.','black-mulch.jpg'),
('choosing-the-right-decorative-rock','Choosing the Right Decorative Rock for Your Yard','From bright Crystal White to dramatic Majestic Midnight, learn which decorative rock fits your design.','Decorative rock is a long-lasting alternative to mulch, requiring no annual top-up. Lighter rocks like Crystal White brighten shaded areas; darker rocks like Majestic Midnight add modern contrast. Consider scale: smaller stones (20mm) suit borders, larger stones (40mm+) suit feature areas.','crystal-white-rock.jpg'),
('spring-landscape-prep','Spring Landscape Prep Checklist','Five quick steps to wake your yard up after winter.','1) Rake out winter debris. 2) Top up mulch in beds to 3" depth. 3) Aerate compacted lawn areas. 4) Edge beds for a crisp finish. 5) Refresh decorative rock borders. Need supplies? We deliver across the city.','garden-mix.jpg');
